version: '2'

services:
  open-ldap:
    image: 'osixia/openldap:1.4.0'
    ports:
      - '389:389'
      - '636:636'
    environment:
      - LDAP_ORGANISATION=My Company
      - LDAP_ADMIN_PASSWORD=admin
      - LDAP_DOMAIN=openldap.spring.poc.com
